'use client';

import { use, useEffect, useState } from 'react';
import { Copy, Check, FileJson2 } from 'lucide-react';
import PageHeader from '@/components/PageHeader';
import ArrayInput from '@/components/reddit/ArrayInput';
import { apiGet, apiFetch, ApiError } from '@/lib/api';
import { buildProjectImportPrompt } from '@/modules/reddit/import-prompts';
import type { RedditModuleConfig } from '@/lib/types';

const EMPTY: RedditModuleConfig = {
  companyDescription: '',
  targetCustomer: '',
  productService: '',
  targetSubreddits: [],
  keywords: [],
  brandMentionStyle: '',
  forbiddenPhrases: [],
};

const normalizeSub = (s: string) => s.replace(/^\/?r\//i, '').trim();
const strList = (v: unknown): string[] | undefined =>
  Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string' && x.trim().length > 0) : undefined;
const str = (v: unknown): string | undefined => (typeof v === 'string' ? v : undefined);

export default function RedditSettingsPage({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = use(params);
  const [config, setConfig] = useState<RedditModuleConfig | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);

  // Bulk import: paste a JSON object (usually generated by the "Copy AI prompt"
  // button below, pasted into any LLM) to fill the form in one shot.
  const [importOpen, setImportOpen] = useState(false);
  const [importJson, setImportJson] = useState('');
  const [companyId, setCompanyId] = useState('');
  const [importErr, setImportErr] = useState<string | null>(null);
  const [importNote, setImportNote] = useState<string | null>(null);
  const [copiedPrompt, setCopiedPrompt] = useState(false);

  useEffect(() => {
    apiGet<{ config: RedditModuleConfig }>(`/api/projects/${projectId}/reddit/config`)
      .then((r) => setConfig(r.config))
      .catch(() => setConfig(EMPTY));
  }, [projectId]);

  const set = <K extends keyof RedditModuleConfig>(k: K, v: RedditModuleConfig[K]) => {
    setConfig((c) => (c ? { ...c, [k]: v } : c));
    setSaved(false);
  };

  async function copyPrompt() {
    await navigator.clipboard.writeText(buildProjectImportPrompt(companyId));
    setCopiedPrompt(true);
    setTimeout(() => setCopiedPrompt(false), 1600);
  }

  // Fill the form from pasted JSON. Only applies the fields the settings form
  // owns (the Reddit config). `name`/`websiteUrl` in the schema belong to the
  // project itself, set when the project is created — noted, not applied here.
  function fillFromJson() {
    setImportErr(null);
    setImportNote(null);
    let parsed: unknown;
    try {
      parsed = JSON.parse(importJson);
    } catch {
      setImportErr('That is not valid JSON.');
      return;
    }
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      setImportErr('Expected a single JSON object like the schema in the prompt.');
      return;
    }
    const p = parsed as Record<string, unknown>;
    setConfig((c) => {
      const base = c ?? EMPTY;
      return {
        companyDescription: str(p.companyDescription) ?? base.companyDescription,
        targetCustomer: str(p.targetCustomer) ?? base.targetCustomer,
        productService: str(p.productService) ?? base.productService,
        targetSubreddits: strList(p.targetSubreddits)?.map(normalizeSub) ?? base.targetSubreddits,
        keywords: strList(p.keywords) ?? base.keywords,
        brandMentionStyle: str(p.brandMentionStyle) ?? base.brandMentionStyle,
        forbiddenPhrases: strList(p.forbiddenPhrases) ?? base.forbiddenPhrases,
      };
    });
    setSaved(false);
    setImportOpen(false);
    setImportJson('');
    if (p.name || p.websiteUrl) {
      setImportNote('Filled the form. Name and website come from the project itself — not changed here. Review, then Save.');
    } else {
      setImportNote('Filled the form from JSON. Review, then Save.');
    }
  }

  async function save(e: React.FormEvent) {
    e.preventDefault();
    if (!config || busy) return;
    setBusy(true);
    setError(null);
    try {
      const r = await apiFetch<{ config: RedditModuleConfig }>(`/api/projects/${projectId}/reddit/config`, {
        method: 'PUT',
        body: JSON.stringify(config),
      });
      setConfig(r.config);
      setSaved(true);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Could not save.');
    } finally {
      setBusy(false);
    }
  }

  if (!config) return <p className="text-dim small">Loading…</p>;

  return (
    <>
      <PageHeader
        title="Reddit settings"
        description="What this client does, where to look, and how the brand may be mentioned."
      />

      <form className="sections" onSubmit={save}>
        <section className="card">
          <div className="card-head">
            <h3>
              <FileJson2 size={15} style={{ verticalAlign: '-2px', marginRight: 6 }} />
              Bulk import from JSON
            </h3>
            <button type="button" className="btn btn-ghost btn-sm" onClick={() => setImportOpen((o) => !o)}>
              {importOpen ? 'Hide' : 'Open'}
            </button>
          </div>
          {importOpen ? (
            <div className="stack">
              <p className="text-dim small">
                Ask any LLM to generate the config, then paste the JSON here to fill the form. Copy the
                ready-made prompt below — it names the company so the model doesn&apos;t mix it up with
                anything else in your chat.
              </p>
              <div className="row">
                <input
                  value={companyId}
                  onChange={(e) => setCompanyId(e.target.value)}
                  placeholder="Which company is this for? (name or URL)"
                  style={{ maxWidth: 360 }}
                />
                <button type="button" className="btn btn-secondary btn-sm" onClick={copyPrompt}>
                  {copiedPrompt ? <Check size={13} /> : <Copy size={13} />}{' '}
                  {copiedPrompt ? 'Copied' : 'Copy AI prompt'}
                </button>
              </div>
              <label className="field" style={{ maxWidth: 640 }}>
                <span>Paste the JSON the model returned</span>
                <textarea
                  value={importJson}
                  onChange={(e) => setImportJson(e.target.value)}
                  placeholder='{ "companyDescription": "…", "targetSubreddits": ["budget", …], … }'
                  rows={6}
                />
              </label>
              {importErr && <p className="text-error small">{importErr}</p>}
              <div className="row">
                <button
                  type="button"
                  className="btn btn-primary btn-sm"
                  onClick={fillFromJson}
                  disabled={!importJson.trim()}
                >
                  Fill form
                </button>
                <button
                  type="button"
                  className="btn btn-ghost btn-sm"
                  onClick={() => {
                    setImportJson('');
                    setImportErr(null);
                  }}
                >
                  Clear
                </button>
              </div>
            </div>
          ) : (
            <p className="text-dim small">
              Have an LLM draft the whole config, then paste it in. Open to copy the prompt.
            </p>
          )}
        </section>

        {importNote && <p className="text-success small">{importNote}</p>}

        <section className="card">
          <div className="card-head">
            <h3>The client</h3>
          </div>
          <div className="stack">
            <label className="field" style={{ maxWidth: 640 }}>
              <span>What they do</span>
              <textarea
                value={config.companyDescription}
                onChange={(e) => set('companyDescription', e.target.value)}
                placeholder="One or two sentences a stranger would understand."
              />
            </label>
            <label className="field" style={{ maxWidth: 640 }}>
              <span>Who it&apos;s for</span>
              <textarea
                value={config.targetCustomer}
                onChange={(e) => set('targetCustomer', e.target.value)}
                placeholder="The person with the problem."
              />
            </label>
            <label className="field" style={{ maxWidth: 640 }}>
              <span>Product or service</span>
              <textarea
                value={config.productService}
                onChange={(e) => set('productService', e.target.value)}
                placeholder="What they actually sell."
              />
            </label>
          </div>
        </section>

        <section className="card">
          <div className="card-head">
            <h3>Where to look</h3>
          </div>
          <div className="stack">
            <label className="field" style={{ maxWidth: 640 }}>
              <span>Subreddits</span>
              <ArrayInput
                value={config.targetSubreddits}
                onChange={(v) => set('targetSubreddits', v)}
                placeholder="budget, personalfinance…"
              />
              <span className="text-dim small">
                r/ prefixes are stripped automatically. Max 20 per fetch.
              </span>
            </label>
            <label className="field" style={{ maxWidth: 640 }}>
              <span>Keywords</span>
              <ArrayInput
                value={config.keywords}
                onChange={(v) => set('keywords', v)}
                placeholder="budgeting app, track spending…"
              />
              <span className="text-dim small">
                Used for search. Multi-word phrases are quoted and OR&apos;d together. Max 15.
              </span>
            </label>
          </div>
        </section>

        <section className="card">
          <div className="card-head">
            <h3>Tone and limits</h3>
          </div>
          <div className="stack">
            <label className="field" style={{ maxWidth: 640 }}>
              <span>Brand mention style</span>
              <textarea
                value={config.brandMentionStyle}
                onChange={(e) => set('brandMentionStyle', e.target.value)}
                placeholder="When, and how, the brand may come up at all."
              />
            </label>
            <label className="field" style={{ maxWidth: 640 }}>
              <span>Forbidden phrases</span>
              <ArrayInput
                value={config.forbiddenPhrases}
                onChange={(v) => set('forbiddenPhrases', v)}
                placeholder="game changer, revolutionary…"
              />
              <span className="text-dim small">
                Claims and hype the client must never make. Passed to the model as hard constraints.
              </span>
            </label>
          </div>
        </section>

        {error && <p className="text-error small">{error}</p>}
        {saved && <p className="text-success small">Saved.</p>}

        <div className="row">
          <button className="btn btn-primary" type="submit" disabled={busy}>
            {busy ? 'Saving…' : 'Save settings'}
          </button>
        </div>
      </form>
    </>
  );
}
